---
IS_TARGET_OPENSTACK: True
OS_AUTH_URL: https://cloud.forgeservicelab.fi:5001/v2.0
OS_USERNAME: <YOUR OPENSTACK USERNAME>
OS_PASSWORD: <YOUR OPENSTACK PASSWORD>
OS_PROJECT: <YOUR OPENSTACK PROJECT>
ALLOWED_IPS:
  - 193.166.24.201
  - 193.166.24.204
web_domain: devel.forgeservicelab.fi
NFS_VIRTUAL_IP: 193.166.24.149
MySQL_VIRTUAL_IP: 193.166.24.148
certificate_prefix: forgeservicelab.fi
drupal_database: forgeservicelab
drupal_revision: development
mailname: forgeservicelab.fi
block_device: /dev/vdb
backends:
  - "{{ hostvars['drupal1']['ansible_ssh_host'] }}"
  - "{{ hostvars['drupal2']['ansible_ssh_host'] }}"
