---
IS_TARGET_OPENSTACK: True
# OS_AUTH_URL: # URL of OpenStack's keystone service

# IMPORTANT!!
# The following two variables hold credentials that will be written
# as plaintext on configuration files on the target machines.
# OS_USERNAME: # Username of OpenStack account allowed to make changes
# OS_PASSWORD: # Password for the account above

# OS_PROJECT: # OpenStack project holding the target VMs
# ALLOWED_IPS: # List of IPs allowed to use the HA backends typically the webserver public IPs. Fill in below
#   - allowed.ip.nr.1 # Public (floating) IP of the first webserver
#   - allowed.ip.nr.2 # Public (floating) IP of the second webserver
# web_domain: # FQDN of the provisioned website
# NFS_VIRTUAL_IP: # Service IP for the NFS HA cluster
# MySQL_VIRTUAL_IP: # Service IP for the MySQL HA cluster
# certificate_prefix: # Name of the SSL certificate files up to but not including file extension
# drupal_database: # Name of the database for Drupal
# mailname: # FQDN for Drupal's outgoing mail server
# block_device: # Device descriptor of the data disk for HA clusters. DO NOT set here if it is not the same on all target machines.
# backends: #List of webservers as seen from the loadbalancer. Fill below.
#   - backend1 # FQDN or IP of the first webserver
#   - backend2 # FQDN or IP of the second webserver
