---
- hosts: 127.0.0.1
  sudo: False
  connection: local

  tasks:
  - name: get roles from gitlab
    git:
      repo=https://git.forgeservicelab.fi/ansible-roles/{{ item }}.git
      dest=roles/{{ item }}
    with_items:
      - common
      - load-balancer
      - drupal
      - ha-disk
      - mysql
      - nfs
