---
- hosts: nfs
  sudo: True
  vars_files:
    - vars/main.yml
  roles:
    - nfs
  tags:
    - nfs

- hosts: mysql
  sudo: True
  vars_files:
    - vars/main.yml
  roles:
    - mysql
  tags:
    - mysql

- hosts: drupal
  sudo: True
  roles:
    - drupal
  tags:
    - drupal

- hosts: loadbalancer
  sudo: True
  roles:
    - load-balancer
  tags:
    - loadbalancer
