---
- hosts: nfs
  sudo: True
  roles:
    - nfs
  tags:
    - nfs

- hosts: mysql
  sudo: True
  roles:
    - mysql
  tags:
    - mysql

- hosts: drupal
  sudo: True
  pre_tasks:
    - apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - php-pear
  roles:
    - role: drush
      drush_install_mode: pear
      drushrc:
        root: /var/www
    - role: memcached
      memcached_cache_size: 1024
    - drupal
  tags:
    - drupal

- hosts: loadbalancer
  sudo: True
  roles:
    - ha-loadbalancer
  tags:
    - loadbalancer
