---
- hosts: nfs
  sudo: True
  roles:
    - nfs
  tags:
    - nfs

- hosts: mysql
  sudo: True
  roles:
    - mysql
  tags:
    - mysql

- hosts: drupal
  sudo: True
  roles:
    - drupal
  tags:
    - drupal

- hosts: loadbalancer
  sudo: True
  roles:
    - ha-loadbalancer
  tags:
    - loadbalancer
