---
- name: Install nginx
  apt:
    pkg=nginx
    state=present

- name: Create tls directory for nginx
  file:
    path=/etc/nginx/tls
    state=directory

- name: Upload certificate file
  copy:
    src=../{{ certificate_path }}/{{ certificate_prefix }}.crt
    dest=/etc/nginx/{{ certificate_path }}/{{ certificate_prefix }}.crt
    owner=root
    group=root
    mode=0644
  notify:
    - restart nginx

- name: Upload certificate key file
  copy:
    src=../{{ certificate_path }}/{{ certificate_prefix }}.key
    dest=/etc/nginx/{{ certificate_path }}/{{ certificate_prefix }}.key
    owner=root
    group=root
    mode=0600
  notify:
    - restart nginx

- name: Configure nginx
  template:
    src=../templates/nginx.j2
    dest=/etc/nginx/sites-available/default
    owner=root
    group=root
    mode=0644
  notify:
    - restart nginx

- name: Install HAProxy
  apt:
    pkg=haproxy
    state=present

- name: Enable HAProxy
  lineinfile:
    dest=/etc/default/haproxy
    regexp=^ENABLED
    line='ENABLED=1'
  notify:
    - restart haproxy

- name: Configure HAProxy
  template:
    src=../templates/haproxy.j2
    dest=/etc/haproxy/haproxy.cfg
    owner=root
    group=root
    mode=0644
  notify:
    - restart haproxy

- name: Ensure nginx is up
  service:
    name=nginx
    state=started

- name: Ensure haproxy is up
  service:
    name=haproxy
    state=started
