---
- name: Partition the data disk
  shell: 'echo "n\np\n1\n\n+150M\nn\np\n2\n\n\nt\n2\n8e\nw" | fdisk /dev/{{ block_device }}'
  when: not ansible_devices.{{ block_device }}.partitions

- name: Install LVM
  apt:
    pkg=lvm2
    state=present

- name: Setup the LVM Volume Group
  lvg:
    vg=data
    pvs="/dev/{{ block_device }}2"

- name: Setup the LV Logical Volume
  lvol:
    vg=data
    lv="{{ group_names[1] }}"
    size=100%VG

- name: Format the Logical Volume
  filesystem:
    fstype=ext4
    dev="/dev/data/{{ group_names[1] }}"

- name: Zero-out the head of the metadata partition
  shell: "dd if=/dev/zero of=/dev/{{ block_device }}1 bs=1M count=128"

- name: Install DRBD
  apt:
    pkg=drbd8-utils
    state=present

- name: Configure DRBD
  template:
    src=../templates/drbd.j2
    dest=/etc/drbd.conf
    owner=root
    group=root
    mode=0644

- name: Install the drbd module
  modprobe:
    name=drbd
    state=present

- name: Initialize the DRBD metadata
  shell: "drbdadm create-md {{ group_names[1] }}"
  notify: restart drbd

- meta: flush_handlers

- name: Invalidate DRBD on secondary node
  shell: "drbdadm invalidate {{ group_names[1] }}"
  when: inventory_hostname.endswith('2')
  notify: restart drbd

- name: Set DRBD primary
  shell: "drbdadm primary {{ group_names[1] }}"
  when: inventory_hostname.endswith('1')
  notify: restart drbd

- name: Install Heartbeat
  apt:
    pkg=heartbeat
    state=present

- name: Configure Heartbeat
  template:
    src=../templates/hb_ha.cf.j2
    dest=/etc/heartbeat/ha.cf


- name: Configure Heartbeat Resources
  template:
    src=../templates/hb_haresources.j2
    dest=/etc/heartbeat/haresources


- name: Configure Heartbeat Auth
  template:
    src=../templates/hb_authkeys.j2
    dest=/etc/heartbeat/authkeys
    owner=root
    group=root
    mode=0600
